### ISSUE TITLE
Implement a binary tree in C++

### ISSUE THREAD

**Issue by larissalages** [larissalages/code_problems#13]
The code should go inside data_structures

**Comment by adenashameem** [comment]
Hey can i take this up please?

**Comment by Bhavik-Ardeshna** [comment]
Hey can i work on this plzzzz

**Comment by larissalages** [comment]
sure @Bhavik-Ardeshna !

**Comment by larissalages** [comment]
Hello @adenashameem ! I will assign to you because you asked me first

**Comment by aaksah1234** [comment]
hello @larissalages , I wish to add more functionality to the code & I have also raised an issue for the same #127 . Can you assign it to me & label my pr as hackatober-accepted.
