### ISSUE TITLE
Remove duplicated folder on data_structures

### ISSUE THREAD

**Issue by larissalages** [larissalages/code_problems#184]
data_structures now has a folder called C++ and another called Cpp, they should be merged because it is the same language. Move the files from one folder to another and delete the old folder.

**Comment by ysnarafat** [comment]
assign me

**Comment by Rutuja07** [comment]
Hey I am interested in doing it could you please assign it to me.

**Comment by 19isha98** [comment]
Hey I am interested in doing it could you please assign it to me.
