### ISSUE TITLE
Implement quick sort in C++

### ISSUE THREAD

**Issue by larissalages** [larissalages/code_problems#2]
We only have quicksort in Python, please implement in C++.
The code should be inside the folder "classical_algorithms"

**Comment by soumya997** [comment]
Hello 👋 @larissalages I am new to the open-source ecosystem and also in the Hacktoberfest right now, it will be really a good first issue for me. **Can you assign this issue to me, so that I can work on it?**

**Comment by larissalages** [comment]
> Hello 👋 @larissalages I am new to the open-source ecosystem and also in the Hacktoberfest right now, it will be really a good first issue for me. **Can you assign this issue to me, so that I can work on it?**

sure @soumya997 !

**Comment by dikshantmali** [comment]
is there any issue with my code @larissalages. if yes then suggest me the way to fix it. so that I can make changes

**Comment by dikshantmali** [comment]
@larissalages if my commit is suitable then please merge it.

**Comment by soumya997** [comment]
@dikshantmali , as it is already assigned to me so I would like to that. 
And I am new to open source and I am taking it as one of my Hacktoberfest contributions as the issue has been tagged as **Hacktoberfest** .
I know how to do that, as I am taking it as my **Hacktoberfest** contribution that's why i did not make any PR.
it will be very helpful for me if you kindly revert the PR.

**Comment by dikshantmali** [comment]
Sure brother

**Comment by dikshantmali** [comment]
> @dikshantmali , as it is already assigned to me so I would like to that.
> And I am new to open source and I am taking it as one of my Hacktoberfest contributions as the issue has been tagged as **Hacktoberfest** .
> I know how to do that, as I am taking it as my **Hacktoberfest** contribution that's why i did not make any PR.
> it will be very helpful for me if you kindly revert the PR.

**Comment by dikshantmali** [comment]
@soumya997 all the best for Hacktoberfest. I am also participating the first time but if you want to contribute to it you are welcome.

**Comment by soumya997** [comment]
> @soumya997 all the best for Hacktoberfest. I am also participating the first time but if you want to contribute to it you are welcome.

Thank you.
I will surely work on it and will try to make PR at the beginning of October.

**Comment by imrahul361** [comment]
@larissalages can I work on it?

**Comment by kartikeysingh6** [comment]
> We only have quicksort in Python, please implement in C++.
> The code should be inside the folder "classical_algorithms"

I can do that for you.

**Comment by kartikeysingh6** [comment]
> We only have quicksort in Python, please implement in C++.
> The code should be inside the folder "classical_algorithms"

**DONE!**
https://github.com/larissalages/code_problems/pull/47

**Comment by imrahul361** [comment]
@kartikeysingh6 you should ask and get issue assigned before a PR.

**Comment by kartikeysingh6** [comment]
> @kartikeysingh6 you should ask and get issue assigned before a PR.

I'm relatively new here, how can I issue an assign? Also I've already made PR, will it get rejected?

**Comment by imrahul361** [comment]
Ask Author to assign you before u pull a request. @kartikeysingh6

**Comment by kartikeysingh6** [comment]
> We only have quicksort in Python, please implement in C++.
> The code should be inside the folder "classical_algorithms"

Hey @larissalages , I know you've already assigned this task to @soumya997 but it has been 13 days and no progress has been made, if you could assign this task to me I'd be grateful and I've already done the task and assigned a PR.

Thank you,
Kartikey Singh

**Comment by soumya997** [comment]
I will be making the PR by tomorrow, I got involved to other Repos actually. My bad.
But, i promise it will be done tomorrow.
