### ISSUE TITLE
C++ solutions for leetcode problems

### ISSUE THREAD

**Issue by jaesharma** [larissalages/code_problems#29]

**Comment by yunusbulutt** [comment]
Hello, which section would you like it added to?

**Comment by jaesharma** [comment]
i don't understand what do you mean by that. I have some solutions in C++ for leetcode problems, i want to contribute. can you assign this issue to me.

**Comment by jaesharma** [comment]
hey @larissalages  I would like to work on this, can you assign this to me.

**Comment by yunusbulutt** [comment]
> i don't understand what do you mean by that. I have some solutions in C++ for leetcode problems, i want to contribute. can you assign this issue to me.


I asked if you would like me to make a custom space for C ++. It doesn't matter, you can assign it to me.

**Comment by yunusbulutt** [comment]
I submited pull request. I would be glad if you merge :)

**Comment by larissalages** [comment]
> Hello, which section would you like it added to?

hello @jaesharma , should go inside leetcode/c++

**Comment by larissalages** [comment]
> I submited pull request. I would be glad if you merge :)

I will, thanks @yunusbulutt

**Comment by yunusbulutt** [comment]
your welcome @larissalages :)

**Comment by cdeepanshu** [comment]
Added leetcode question please merge
