### ISSUE TITLE
Implement Merge Sort in C++

### ISSUE THREAD

**Issue by larissalages** [larissalages/code_problems#4]
Code should go inside the folder classical_algorithms

**Comment by gokulkannan7** [comment]
I would love to contribute to this, can u assign it to me?

**Comment by gokulkannan7** [comment]
and since it is a part of hacktoberfest, should I put a PR in the month of October?

**Comment by larissalages** [comment]
Sure @gokulkannan7 !

**Comment by gokulkannan7** [comment]
hello @larissalages, I have opened a PR
