### ISSUE TITLE
Koko Eating Bananas (Leetcode)

### ISSUE THREAD

**Issue by taramatt93** [larissalages/code_problems#421]
I can add my JS solution to the Leetcode problem 'Koko Eating Bananas' 
https://leetcode.com/problems/koko-eating-bananas/

@larissalages If you wouldn't mind assigning this to me?

**Comment by larissalages** [comment]
assigned @taramatt93 !

**Comment by taramatt93** [comment]
Ah, any chance of this getting the Hacktoberfest label on it? No worries if not, I've already done my 4 PRs 👍

**Comment by larissalages** [comment]
sure @taramatt93
