### ISSUE TITLE
Remove extra folder for Hackerrank

### ISSUE THREAD

**Issue by larissalages** [larissalages/code_problems#62]
We have two folder for Hackerrank in the repo, Hackerrank and hackerrank, move the files from one folder to another and remove the extra folder.

**Comment by rheimon1** [comment]
Hey, i'd like to do this, could you assign to me?

**Comment by avk29** [comment]
Hi, I'd like to work on this, would like if you can assign it to me. (I'm also super new to open source so any specific instructions/help from your end would be appreciated!)

**Comment by madhhuurrii** [comment]
Hii @larissalages i would like to work on this issue ,please assign me
