### ISSUE TITLE
Implement Quick Sort in Java

### ISSUE THREAD

**Issue by larissalages** [larissalages/code_problems#7]
Code should go inside the folder classical_algorithms

**Comment by harisriaz17** [comment]
Hey, can I do this? Since it's not October yet, I will make the PR for this on 1st October.

**Comment by debangeedas** [comment]
Hey! I would like to give a shot at this!

**Comment by larissalages** [comment]
Hello @harisriaz17 ! I assigned to you since you commented first, thank you both! :)
